# SCons environment
env = Environment()

# Copy file1 → file2 using command.sh
# Inject an error if file1 starts with 'bad"
file2 = env.Command(
    target='file2',
    source='file1',
    action='./command.sh $SOURCE $TARGET'
)

# Make 'file2' the default target
Default(file2)
