env=Environment()


if False:
    scons_subprocess_call = (lambda target, source, env
                             : subprocess.call(env['ARGS'], source[0]))
    data = env.Command(
        source = "foo.pl",
        target = "bar.log",
        action = scons_subprocess_call,
        ARGS   = ['homo sapiens', 'Reference GRCh'])
else:
    data = env.Command(
        source = "./foo.pl",
        target = "bar.log",
        action = "${SOURCE.abspath} $ARGS  > $TARGET",
        ARGS   = ['homo sapiens', 'Reference GRCh'])

