class foo:
    def __init__(self, arg):
        self.arg = arg

    def __call__(self, target, source, env, for_signature):
        return self.arg + " bar"

# Will expand $BAR to "my argument bar baz"
env=Environment(FOO=foo, BAR="${FOO('my argument')} baz")

other_foo = foo(' Bananas')
env['BANANAS'] = other_foo

print("->%s"%env.subst("$BAR"))
print("->%s"%env.subst("$BANANAS"))
