e = DefaultEnvironment()
 
mycc = e.Command(target="mycc",
                 source="/usr/bin/gcc",
                 action="cp $SOURCE $TARGET")
 
e.Replace(CC = mycc[0].abspath)
 
e.Program(target='testapp', source='test.c')
