DefaultEnvironment(tools=[])
env=Environment(tools=[])

x=env.Command('blahx', ['one', 'two','three'],["echo SOURCES.abspath=${SOURCES.abspath}"])
y=env.Command('blahy', ['one', 'two','three'],["echo CHANGED_SOURCES=${CHANGED_SOURCES.abspath}"])
z=env.Command('blahz', ['one', 'two','three'],["echo CHANGED_TARGETS=${CHANGED_TARGETS.abspath}"])


# breakpoint()
