def build_it(target, source, env):
    # breakpoint()
    print("build_it: Goodbye")
    return 0

def string_it(target, source, env):
    # print("string it: Goodbye")
    return("string it: Goodbye")

s = Action(build_it, string_it)

show = Command("show",  "", "@echo Hello")
# show = Command("show",  "", s)

# show = Alias("foo", show, "@echo foo alias")
show = Alias("foo", show)

AddPostAction(show,  s)

